FROM node:24-bookworm

WORKDIR /app

# Copy package files
COPY server/package*.json .
RUN npm install

# Copy and run server after start container
COPY --chmod=755 server/entrypoint.sh .
RUN chmod +x entrypoint.sh

EXPOSE 3000
ENTRYPOINT ["./entrypoint.sh"]